version: '3.7'
services:
  database:
    image: postgres:13
    container_name: walki-database
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # networks:
    #   - walki_network

#   backend:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: walki-service
#     ports: 
#       - '${PORT}:${PORT}'
#     depends_on:
#       - database
#     volumes:
#       - ./src:/app/src
#     networks:
#       - walki_network

# networks:
#   walki_network:
#     driver: bridge

volumes:
  postgres_data: